# Repository settings set via https://github.com/probot/settings

repository:
  has_downloads: false

labels:
  - name: help-wanted
    color: 0e8a16
  - name: more-information-needed
    color: d93f0b
  - name: bug
    color: b60205
  - name: feature
    color: 1d76db
  - name: good first issue
    color: "5319e7"

# Not currently implemented by probot/settings, but manually implemented in script/deploy
branch_protection:
  required_status_checks:
    strict: true
  required_pull_request_reviews:
    require_code_owner_reviews: true
